// <auto-generated />
using CTEDSDigitalMenu.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTEDSDigitalMenu.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("CTEDSDigitalMenu.Domains.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1,
                            Name = "Entry"
                        },
                        new
                        {
                            ItemTypeId = 2,
                            Name = "Main"
                        },
                        new
                        {
                            ItemTypeId = 3,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("CTEDSDigitalMenu.Domains.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Description = "Siri desfiado e temperado servido em sua casca",
                            ItemTypeId = 1,
                            Name = "Casquinha de Siri",
                            Price = 23.989999999999998
                        },
                        new
                        {
                            MenuItemId = 2,
                            Description = "Camatões refogados com leite de coco, pimentões, tomates e cebola",
                            ItemTypeId = 2,
                            Name = "Moqueca de Camarão",
                            Price = 54.990000000000002
                        },
                        new
                        {
                            MenuItemId = 3,
                            Description = "Brigadeiro cremoso de colher com farofa de paçoca",
                            ItemTypeId = 3,
                            Name = "Brigadeiro de Colher",
                            Price = 18.989999999999998
                        });
                });

            modelBuilder.Entity("CTEDSDigitalMenu.Domains.MenuItem", b =>
                {
                    b.HasOne("CTEDSDigitalMenu.Domains.ItemType", "ItemType")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("CTEDSDigitalMenu.Domains.ItemType", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
